### PR TITLE
features

### PR DESCRIPTION
**Pull request by bananaturtlesandwich**
make encryption and compression capabilities optional, e.g for game-specific tools

### CODE REVIEW

**Comment by trumank** [comment]
I think I like conditionally compiling out whole functions rather than change arguments based on features (at least for the public API). How does this look?

I also fixed some clippy and test issues with particular feature combinations. Turns out `cargo test-all-features` is a great tool for checking these.

**Comment by bananaturtlesandwich** [comment]
Personally I think that conditionally compiling arguments is much cleaner.
I don't see the point of 2 different functions for when encryption is enabled when one takes an option anyway. Also, if you have disabled the features that are on by default, then you clearly have the intent of not using the keys so why bother having a wrapper type that only has one variant internally? It's still functionally the same as before but now it's just been overengineered in my opinion

**Comment by bananaturtlesandwich** [comment]
Also ooh didn't know about `test-all-features` that's very useful

**Comment by trumank** [comment]
The difference is that function signatures remain constant for all combinations of features. I find it annoying when looking up docs and then seeing functions have a different set of args than what I see in my editor.

**Comment by bananaturtlesandwich** [comment]
Then I can change the docs. Shrimple

**Comment by bananaturtlesandwich** [comment]
Then I can change the docs. Shrimple. Besides, if you're using something like lsp you would see the version you will be using.

**Comment by bananaturtlesandwich** [comment]
wait there's no docs to even change wdym 💀

**Comment by bananaturtlesandwich** [comment]
redoing this in new PR since I want to avoid making a merge commit and it's better from fresh anyway

**Pull request closed without merging**
