### PR TITLE
Oodle stuff

### PR DESCRIPTION
**Pull request by bananaturtlesandwich**
- it is now the responsibility of the caller to provide the `OodleLZ_Decompress` function to repak - this allows flexibility in how the problem of oodle being proprietary is handled
- repak-cli still uses the whole downloading a dll off discord thing
- THIS IS A BREAKING CHANGE FOR OTHER PROJECTS

### CODE REVIEW

**Comment by bananaturtlesandwich** [comment]
not sure if it should be kept as a feature since there's no dependencies it needs

**Comment by trumank** [comment]
I now remember why I was hesitant to implement this. The simple implementation creates a messy API and means oodle must always be loaded up front whether it's actually used or not. I think these could be alleviated by using the builder pattern and instead of passing a function pointer directly, pass a function which can be called to fetch oodle only when necessary:

```rust
fn get_oodle() -> Result<DECOMPRESS> {
    // lazily fetch the decompress function when necessary
}

let pak_reader = PakReaderBuilder::new(reader)
    .oodle(get_oodle)
    .build()?;
```

I think this may also work really nicely for entering AES keys.

**Comment by bananaturtlesandwich** [comment]
ooh that's a really nice point about the builder pattern - with encryption disabled the `.aes()` can be missed
as for the second point i think that would be better as a separate package on this repo

**Comment by bananaturtlesandwich** [comment]
oh wait nvm it's salvageable lol

**Comment by bananaturtlesandwich** [comment]
might be better to have a oodle init function rather than pass in builder since it only needs to be called once

**Comment by bananaturtlesandwich** [comment]
this should be good now

**Comment by bananaturtlesandwich** [comment]
wait need to fix tests

**Comment by bananaturtlesandwich** [comment]
fixed now

**Pull request merged**
